import * as category from "./category.validations";
import * as blog from "./blog.validation";
import * as user from "./user.validation";
import * as event from "./event.validation";
import * as stays from "./stays.validation";
export const EventValidation = event;
export const CategoryValidation = category;
export const BlogValidation = blog;
export const UserValidation = user;
export const StaysValidation = stays;
