import * as category from "./category.controller";
import * as blog from "./blogs.controller";
import * as user from "./user.controller";
import * as event from "./event.controller";
import * as destination from "./destination.controller";
import * as stays from "./stays.controller";
import * as chat from "./chat.controller";
import * as image from "./image.controller";
import * as comment from "./comment.controller";
import * as tickets from "./event-ticket.controller";
export const CategoryController = category;
export const BlogController = blog;
export const UserController = user;
export const EventController = event;
export const DestinationController = destination;
export const StaysController = stays;
export const ChatController = chat;
export const ImageController = image;
export const CommentController = comment;
export const TicketController = tickets;
