import userModel from "./user.model";
import categoryModel from "./category.model";
import blogModel from "./blogs.model";
import eventModel from "./event.model";
import destinationModel from "./destination.model";
import staysModel from "./stays.model";
import chatModel from "./chat.model";
import notificationsModel from "./notifications";
import postcontentModel from "./post-content.model";
import commentModel from "./comments.model";
export const User = userModel;
export const Category = categoryModel;
export const Blog = blogModel;
export const Event = eventModel;
export const Destination = destinationModel;
export const Stays = staysModel;
export const Chat = chatModel;
export const Notification = notificationsModel;
export const PostContent = postcontentModel;
export const Comments = commentModel;
